version: '3.3'

services:

  funnymovies-frontend:
    # build:
    #   context: .
    #   args:
    #     - VITE_BASE_API=http://funnymovies.loi-tra
    # image: funnymovies-frontend
    image: nginx:stable-alpine
    container_name: funnymovies-frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./dist:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=funny-movies-dev.loitra.xyz
      - LETSENCRYPT_HOST=funny-movies-dev.loitra.xyz
      - LETSENCRYPT_EMAIL=trathailoi@gmail.com
      - API_URL=http://funnymovies-backend
      - API_HOST=funnymovies-backend
    # command: nginx -g 'daemon off;'
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://funny-movies-dev.loitra.xyz/nginx-health || exit 1"]
      timeout: 5s
      retries: 10
    depends_on:
      - funnymovies-backend
  
  funnymovies-backend:
    container_name: funnymovies-backend
    # build:
    #   context: ./backend
    #   target: production
    build: ./backend
    image: funnymovies-backend
    restart: on-failure
    env_file:
      - ./backend/.env
    environment:
      - MODE=PROD
      - CLIENT_URL=https://funny-movies-dev.loitra.xyz
      - POSTGRES_HOST=funnymovies-db
    depends_on:
      - funnymovies-db
    tty: true
    stdin_open: true
  
  funnymovies-db:
    image: postgres:9.6
    container_name: funnymovies-db
    restart: always
    env_file:
      - ./backend/.env # to get the following env vars: POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    #   - ./data/postgres:/data/postgres (?)
  
volumes:
  postgres-data:

networks:
  default:
    external:
      name: nginx-proxy-net
