version: '3.3'

services:
  funnymovies-frontend:
    build:
      context: .
      args:
        - VITE_BASE_API=http://funnymovies.loi-tra
    image: funnymovies-frontend
    container_name: funnymovies-frontend
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=funnymovies.loi-tra
      - API_URL=http://funnymovies-backend:3000
      - API_HOST=funnymovies-backend
    command: nginx -g 'daemon off;'
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://funnymovies.loi-tra/nginx-health || exit 1"]
      timeout: 5s
      retries: 10
    depends_on:
      - funnymovies-backend

networks:
  default:
    name: funnymovies-local-net
    driver: bridge
  
volumes:
  postgres-data:
