version: '3'

services:
  funnymovies-testing-db:
    image: postgres
    container_name: funnymovies-testing-db
    restart: always
    env_file:
      - .env.test # to get the following env vars: POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB
    ports:
      - "5433:5432" # diffent port for test
    volumes:
      - postgres-testing-data:/var/lib/postgresql/data
    #   - ./data/postgres:/data/postgres (?)

networks:
  default:
    name: funnymovies-testing-net
    driver: bridge

volumes:
  postgres-testing-data: