version: '3'

services:
  funnymovies-backend:
    container_name: funnymovies-backend
    build:
      context: .
      target: development
    image: funnymovies-backend
    restart: on-failure
    command: npm run start -- --watch
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    environment:
      - MODE=DEV
      - CLIENT_URL=http://localhost:8080
      - POSTGRES_HOST=funnymovies-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - funnymovies-db
    tty: true
    stdin_open: true

  funnymovies-db:
    image: postgres
    container_name: funnymovies-db
    restart: always
    env_file:
      - .env # to get the following env vars: POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    #   - ./data/postgres:/data/postgres (?)

networks:
  default:
    # name: funnymovies-local-net
    driver: bridge

volumes:
  postgres-data: